<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MAIN" Id="{05dceb2c-0d53-456d-b815-0e85d7a4d0aa}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	input1: BOOL;
	output1:BOOL;
	counter : int;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[counter := counter +1;
light();]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>